### ISSUE TITLE
Loader fails to run along LoaderOptionsPlugin() in webpack2

### ISSUE THREAD

**Issue by korya** [peerigon/extract-loader#16]
When I use `extract-loader` along `LoaderOptionsPlugin()` in webpack2 it constantly fails with the following error:

```
...
Module build failed: TypeError: Cannot read property 'publicPath' of undefined
    at Object.extractLoader (/Users/korya/dev/plntr/embedded_fw/recipes-planitar/survey/node_modules/extract-loader/lib/extractLoader.js:47:102)
```

Versions:
```sh
webpack: 2.2.0-rc.3
extract-loader: 0.1.0
```

Relevant parts of my config
```js
  ...
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'eslint-loader',
      },
      ...
      {
        test: /\.html$/,
        loader: 'file-loader!extract-loader!html-loader',
      },
      ...
    ],
  },

  plugins: [
    new webpack.LoaderOptionsPlugin({
      options: {
        eslint: {
          configFile: '.eslintrc.yml',
          emitErrors: true,
          failOnError: true,
        },
      },
    }),
  ],
...
```

As soon as I remove (delete or comment out) the `new webpack.LoaderOptionsPlugin({...})` lines, everything works as expected.

**Comment by korya** [comment]
I found another workaround for the problem: add `options.output` property to object provided to `LoaderOptionsPlugin()`. That is:

```js
  ...
  plugins: [
    new webpack.LoaderOptionsPlugin({
      options: {
        output: {},               // <--- this solves the issue
        eslint: {
          configFile: '.eslintrc.yml',
          emitErrors: true,
          failOnError: true,
        },
      },
    }),
  ],
  ...
```

**Comment by jhnns** [comment]
The error occurs because the extract-loader tries to derive the `publicPath` from `this.options.output`. If you use the `LoaderOptionsPlugin`, you extend the loader's `this` with your object. The `options` object provided by you does not have the `output` property, that's why there is an error.

The `LoaderOptionsPlugin` should only be used with webpack 1 loaders that read their options from `this`. Most loaders (including the eslint-loader) have been updated to webpack 2 now, so there's no need to use the `LoaderOptionsPlugin` anymore.
